function file=plot_supplementary_figure_s13(root,mode,dataRoot,outputRoot)

if nargin<3 || isempty(dataRoot), dataRoot=resolve_figure_data_root(root,mode); end
if nargin<4 || isempty(outputRoot), outputRoot=resolve_figure_output_root(root,mode); end
sourceFile=fullfile(dataRoot,'Analytical','Analytical_results.mat');
if ~isfile(sourceFile), error('Missing analytical results. Run run_hierarchical_repair_analysis first.'); end
loaded=load(sourceFile,'s13','cfg'); data=loaded.s13; cfg=loaded.cfg;
cfg.output.supp=fullfile(outputRoot,'supplementary');
cfg.figure.fontSize=10;
if ~isfolder(cfg.output.supp), mkdir(cfg.output.supp); end

fig = figure('Color', 'w', 'Units', 'centimeters', ...
    'Position', [2 2 cfg.figure.widthCm cfg.figure.analytical01HeightCm]);
tl = tiledlayout(fig, 2, 2, 'TileSpacing', 'compact', ...
    'Padding', 'compact');

cols = [cfg.colors.blue; cfg.colors.orange; ...
    cfg.colors.green; cfg.colors.red];
theta = data.theta;

axA = nexttile(tl, 1);
hold(axA, 'on');

responseA = data.responseA;

plot(axA, theta, responseA.taskFraction, '-', ...
    'Color', cols(1, :), 'LineWidth', 1.6, ...
    'DisplayName', ...
    '$x_3^{\mathrm{P}}(\theta_{\mathrm{P}})=1-e^{-\theta_{\mathrm{P}}}$');
plot(axA, theta, responseA.connectedFraction, '--', ...
    'Color', cols(2, :), 'LineWidth', 1.5, ...
    'DisplayName', ...
    '$y_3^{\mathrm{P}}(\theta_{\mathrm{P}})=[x_3^{\mathrm{P}}(\theta_{\mathrm{P}})]^4$');
plot(axA, theta, responseA.restoredFraction, ':', ...
    'Color', cols(3, :), 'LineWidth', 1.8, ...
    'DisplayName', ...
    ['$r_3^{\mathrm{P}}=\mathcal{H}_3(y_3^{\mathrm{P}})' ...
    '=(y_3^{\mathrm{P}})^{0.75}$']);

xlim(axA, [0 8]);
ylim(axA, [0 1]);
xlabel(axA, 'Dimensionless time, $\theta_{\mathrm{P}}$', ...
    'Interpreter', 'latex');
ylabel(axA, 'Fraction', 'Interpreter', 'latex');
legend(axA, 'Location', 'southeast', 'Box', 'off', ...
    'Interpreter', 'latex', 'FontSize', 10);
apply_latex_axes_style(axA, cfg);
panel_label(axA, 'a', 10);

axB = nexttile(tl, 2);
hold(axB, 'on');

depthsB=data.depthsB; closedB=data.closedB;
numericalB=data.numericalB; Xnumerical=data.Xnumerical;

for k = 1:numel(depthsB)
    l = depthsB(k);
    lightColor = 0.68 * [1 1 1] + 0.32 * cols(k, :);
    plot(axB, theta, Xnumerical(:, k), '-', ...
        'Color', lightColor, 'LineWidth', 2.8, ...
        'HandleVisibility', 'off');
    plot(axB, theta, closedB.taskFraction(:, k), '--', ...
        'Color', cols(k, :), 'LineWidth', 1.35, ...
        'DisplayName', sprintf('$l=%d$', l));
end

maxError = data.maxError;
text(axB, 0.58, 0.50, ...
    {'$\mathrm{dashed:~closed~form}$'; ...
    '$\mathrm{light\ solid:~numerical}$'; ...
    sprintf('$\\max|e|=%.2g$', maxError)}, ...
    'Units', 'normalized', 'Interpreter', 'latex', ...
    'HorizontalAlignment', 'left', 'VerticalAlignment', 'top', ...
    'FontSize', 10);

xlim(axB, [0 10]);
ylim(axB, [0 1]);
xlabel(axB, 'Dimensionless time, $\theta_{\mathrm{F}}$', ...
    'Interpreter', 'latex');
ylabel(axB, 'Physical completion, $x_l^{\mathrm{F}}$', ...
    'Interpreter', 'latex');
legend(axB, 'Location', 'southeast', 'Box', 'off', ...
    'Interpreter', 'latex', 'FontSize', 10);
apply_latex_axes_style(axB, cfg);
panel_label(axB, 'b', 10);

axC = nexttile(tl, 3);
hold(axC, 'on');

depthsC=data.depthsC; responseC=data.responseC;

plot(axC, theta, responseC.taskFraction(:, 1), 'k-', ...
    'LineWidth', 1.65, ...
    'DisplayName', ...
    '$x_l^{\mathrm{P}}(\theta_{\mathrm{P}})=1-e^{-\theta_{\mathrm{P}}}\;(\forall l)$');
for k = 1:numel(depthsC)
    l = depthsC(k);
    plot(axC, theta, responseC.connectedFraction(:, k), ...
        'Color', cols(k, :), 'LineWidth', 1.4, ...
        'DisplayName', sprintf( ...
        ['$y_{%d}^{\\mathrm{P}}(\\theta_{\\mathrm{P}})' ...
        '=\\left(1-e^{-\\theta_{\\mathrm{P}}}\\right)^{%d}$'], ...
        l, l + 1));
end

xlim(axC, [0 8]);
ylim(axC, [0 1]);
xlabel(axC, 'Dimensionless time, $\theta_{\mathrm{P}}$', ...
    'Interpreter', 'latex');
ylabel(axC, 'Fraction', 'Interpreter', 'latex');
legend(axC, 'Location', 'southeast', 'Box', 'off', ...
    'Interpreter', 'latex', 'FontSize', 10);
apply_latex_axes_style(axC, cfg);
panel_label(axC, 'c', 10);

axD = nexttile(tl, 4);
hold(axD, 'on');

depthsD=data.depthsD; frontierRate=data.frontierRate;
baseCompletion=data.baseCompletion;

plot(axD, theta, frontierRate(:, 1), 'k-', ...
    'LineWidth', 1.65, ...
    'DisplayName', ...
    ['$l=0:\;dx_0^{\mathrm{F}}/d\theta_{\mathrm{F}}' ...
    '=dr_0^{\mathrm{P}}/d\theta_{\mathrm{P}}$']);

for l = 1:max(depthsD)
    parallelRate = (l + 1) .* exp(-theta) .* baseCompletion.^l;
    plot(axD, theta, frontierRate(:, l + 1), '-', ...
        'Color', cols(l, :), 'LineWidth', 1.45, ...
        'DisplayName', sprintf( ...
        '$dx_{%d}^{\\mathrm{F}}/d\\theta_{\\mathrm{F}}$', l));
    plot(axD, theta, parallelRate, '--', ...
        'Color', cols(l, :), 'LineWidth', 1.25, ...
        'DisplayName', sprintf( ...
        '$dr_{%d}^{\\mathrm{P}}/d\\theta_{\\mathrm{P}}$', l));
end

xlim(axD, [0 8]);
ylim(axD, [0 1.02]);
xlabel(axD, 'Dimensionless time, $\theta_{\mathrm{F}}$ or $\theta_{\mathrm{P}}$', ...
    'Interpreter', 'latex');
ylabel(axD, 'Dimensionless completion rate');
legend(axD, 'Location', 'northeast', 'Box', 'off', ...
    'Interpreter', 'latex', 'FontSize', 10, 'NumColumns', 1);
apply_latex_axes_style(axD, cfg);
panel_label(axD, 'd', 10);

stem=fullfile(cfg.output.supp,'Supplementary_Figure_S13');
export_publication_figure(fig,stem,cfg.figure.dpi); file=[stem '.fig'];
close(fig);
end

function apply_latex_axes_style(ax, cfg)
apply_axes_style(ax, cfg);
set(ax, 'TickLabelInterpreter', 'latex', ...
    'LabelFontSizeMultiplier', 1, 'TitleFontSizeMultiplier', 1);
end
