
function make_TableS6_cross_lifeline_timing_summary(supplementaryRoot)

if nargin < 1 || isempty(supplementaryRoot)
    scriptDir = string(fileparts(mfilename("fullpath")));
    moduleRoot = scriptDir;
    emergentRoot = string(fileparts(fileparts(moduleRoot)));
    supplementaryRoot = fullfile(emergentRoot, "outputs", "supplementary");
end

scriptDir = string(fileparts(mfilename("fullpath")));
moduleRoot = scriptDir;
emergentRoot = string(fileparts(fileparts(moduleRoot)));
intermediateRoot = fullfile( ...
    emergentRoot, ...
    "outputs", ...
    "intermediate", ...
    "03_cross_lifeline_timing_coupling");

addpath(scriptDir);

inputMat = fullfile( ...
    intermediateRoot, ...
    "paired_timing_coupling_dataset.mat");

outputDir = fullfile(supplementaryRoot, "source_data");

outXlsx = fullfile( ...
    outputDir, ...
    "SourceData_TableS6.xlsx");

ensureDir(outputDir);

if ~isfile(inputMat)
    error( ...
        "Paired timing/coupling MAT not found:\n%s\n" + ...
        "Run run_01_make_cross_lifeline_timing_coupling_source_data.m first.", ...
        inputMat);
end


S = load( ...
    inputMat, ...
    "Paired");

if ~isfield(S, "Paired")
    error( ...
        "MAT file does not contain Paired:\n%s", ...
        inputMat);
end

T = normalizePairedTable(S.Paired);

if isempty(T)
    error( ...
        "Paired dataset is empty:\n%s", ...
        inputMat);
end

requiredFields = [ ...
    "systemPair", ...
    "rho50_B_over_E", ...
    "rho80_B_over_E", ...
    "rho90_B_over_E", ...
    "rho95_B_over_E", ...
    "deltaT90_B_minus_E", ...
    "deltaT95_B_minus_E"];

assertRequiredFields( ...
    T, ...
    requiredFields, ...
    "Paired");


metricType = [ ...
    "rho"
    "rho"
    "rho"
    "rho"
    "rho"
    "rho"
    "rho"
    "rho"
    "delta"
    "delta"
    "delta"
    "delta"];

pValue = [ ...
    90
    90
    95
    95
    50
    50
    80
    80
    90
    90
    95
    95];

pairType = [ ...
    "EW"
    "EG"
    "EW"
    "EG"
    "EW"
    "EG"
    "EW"
    "EG"
    "EW"
    "EG"
    "EW"
    "EG"];

nRows = numel(metricType);


System_pair = strings(nRows, 1);
metric = strings(nRows, 1);
p = nan(nRows, 1);
pair = strings(nRows, 1);
pairTypeOut = strings(nRows, 1);

Records_n = zeros(nRows, 1);
Median = nan(nRows, 1);
Q25 = nan(nRows, 1);
Q75 = nan(nRows, 1);
Q05 = nan(nRows, 1);
Q95 = nan(nRows, 1);
IQR = nan(nRows, 1);

for i = 1:nRows

    thisMetric = metricType(i);
    thisP = pValue(i);
    thisPairType = pairType(i);

    rhoField = ...
        "rho" + ...
        string(thisP) + ...
        "_B_over_E";

    pairMask = ...
        T.systemPair == thisPairType;

    rhoValues = ...
        double(T.(char(rhoField)));

    if thisP == 90 || ...
            thisP == 95

        deltaField = ...
            "deltaT" + ...
            string(thisP) + ...
            "_B_minus_E";

        deltaValues = ...
            double(T.(char(deltaField)));

        eligibleMask = ...
            pairMask & ...
            isfinite(rhoValues) & ...
            rhoValues > 0 & ...
            isfinite(deltaValues);

    else

        eligibleMask = ...
            pairMask & ...
            isfinite(rhoValues) & ...
            rhoValues > 0;
    end

    if thisMetric == "rho"

        values = ...
            rhoValues(eligibleMask);

    elseif thisMetric == "delta"

        deltaField = ...
            "deltaT" + ...
            string(thisP) + ...
            "_B_minus_E";

        deltaValues = ...
            double(T.(char(deltaField)));

        values = ...
            deltaValues(eligibleMask);

    else

        error( ...
            "Unsupported metric type: %s", ...
            thisMetric);
    end

    q = ...
        quantileLocal( ...
            values, ...
            [0.05 0.25 0.50 0.75 0.95]);

    pairLabel = ...
        pairRatioLabel(thisPairType);

    if thisMetric == "rho"

        systemPairLabel = ...
            "rho_" + ...
            string(thisP) + ...
            "^" + ...
            pairLabel;

    else

        systemPairLabel = ...
            "DeltaT_" + ...
            string(thisP) + ...
            "^" + ...
            pairLabel;
    end

    System_pair(i) = ...
        systemPairLabel;

    metric(i) = ...
        thisMetric;

    p(i) = ...
        thisP;

    pair(i) = ...
        pairLabel;

    pairTypeOut(i) = ...
        thisPairType;

    Records_n(i) = ...
        numel(values);

    Q05(i) = q(1);
    Q25(i) = q(2);
    Median(i) = q(3);
    Q75(i) = q(4);
    Q95(i) = q(5);

    if isfinite(Q25(i)) && ...
            isfinite(Q75(i))

        IQR(i) = ...
            Q75(i) - Q25(i);
    end
end

NumericTable = table( ...
    System_pair, ...
    metric, ...
    p, ...
    pair, ...
    pairTypeOut, ...
    Records_n, ...
    Median, ...
    Q25, ...
    Q75, ...
    Q05, ...
    Q95, ...
    IQR, ...
    'VariableNames', { ...
        'System_pair', ...
        'metric', ...
        'p', ...
        'pair', ...
        'pairType', ...
        'Records_n', ...
        'Median', ...
        'Q25', ...
        'Q75', ...
        'Q05', ...
        'Q95', ...
        'IQR'});


DisplaySystemPair = ...
    NumericTable.System_pair;

DisplayN = ...
    NumericTable.Records_n;

DisplayMedian = strings(nRows, 1);
DisplayQ25Q75 = strings(nRows, 1);
DisplayQ05Q95 = strings(nRows, 1);

for i = 1:nRows

    DisplayMedian(i) = ...
        formatMedian( ...
            NumericTable.Median(i));

    DisplayQ25Q75(i) = ...
        formatInterval( ...
            NumericTable.Q25(i), ...
            NumericTable.Q75(i));

    DisplayQ05Q95(i) = ...
        formatInterval( ...
            NumericTable.Q05(i), ...
            NumericTable.Q95(i));
end

DisplayTable = table( ...
    DisplaySystemPair, ...
    DisplayN, ...
    DisplayMedian, ...
    DisplayQ25Q75, ...
    DisplayQ05Q95, ...
    'VariableNames', { ...
        'System_pair', ...
        'Records_n', ...
        'Median', ...
        'Q25_Q75', ...
        'Q05_Q95'});

if isfile(outXlsx)
    delete(outXlsx);
end

writeTableCompatPortable( ...
    DisplayTable, ...
    outXlsx, ...
    "display_table");

writeTableCompatPortable( ...
    NumericTable, ...
    outXlsx, ...
    "numeric_source");

fprintf( ...
    "Saved supplementary cross-lifeline timing source data:\n%s\n", ...
    outXlsx);



end

function T = normalizePairedTable(T)

if ~istable(T)
    error("Paired must be a table.");
end

if ~ismember( ...
        "systemPair", ...
        string(T.Properties.VariableNames))

    error("Paired must contain systemPair.");
end

T.systemPair = ...
    upper( ...
        strtrim( ...
            string(T.systemPair)));

end

function assertRequiredFields( ...
        T, ...
        requiredFields, ...
        label)

available = ...
    string(T.Properties.VariableNames);

missing = ...
    requiredFields( ...
        ~ismember(requiredFields, available));

if ~isempty(missing)

    error( ...
        "%s is missing required field(s): %s", ...
        label, ...
        strjoin(missing, ", "));
end

end

function label = pairRatioLabel(pairType)

if pairType == "EW"

    label = "W/E";

elseif pairType == "EG"

    label = "G/E";

else

    error( ...
        "Unsupported pair type: %s", ...
        pairType);
end

end

function q = quantileLocal( ...
        values, ...
        probabilities)

values = ...
    sort( ...
        double(values(:)));

values = ...
    values(isfinite(values));

q = ...
    nan(size(probabilities));

if isempty(values)
    return;
end

for i = 1:numel(probabilities)

    probability = ...
        probabilities(i);

    if numel(values) == 1

        q(i) = ...
            values(1);

    else

        position = ...
            1 + ...
            (numel(values) - 1) * ...
            probability;

        lowerIndex = ...
            floor(position);

        upperIndex = ...
            ceil(position);

        if lowerIndex == upperIndex

            q(i) = ...
                values(lowerIndex);

        else

            q(i) = ...
                values(lowerIndex) + ...
                (values(upperIndex) - values(lowerIndex)) * ...
                (position - lowerIndex);
        end
    end
end

end

function textValue = formatMedian(value)

if ~isfinite(value)

    textValue = "";

else

    textValue = ...
        string( ...
            sprintf( ...
                "%.3f", ...
                value));
end

end

function textValue = formatInterval( ...
        lowValue, ...
        highValue)

if ~( ...
        isfinite(lowValue) && ...
        isfinite(highValue))

    textValue = "";
    return;
end

textValue = ...
    "[" + ...
    formatIntervalBound(lowValue) + ...
    "-" + ...
    formatIntervalBound(highValue) + ...
    "]";

end

function textValue = formatIntervalBound(value)

if ~isfinite(value)

    textValue = "";
    return;
end

textValue = ...
    string( ...
        sprintf( ...
            "%.3f", ...
            value));

end

function ensureDir(directoryPath)

if exist(char(directoryPath), 'dir') ~= 7
    mkdir(char(directoryPath));
end

end
