
function make_TableS5_late_loss_fraction_resolution_sensitivity(supplementaryRoot)

if nargin < 1 || isempty(supplementaryRoot)
    scriptDir = string(fileparts(mfilename("fullpath")));
    moduleRoot = scriptDir;
    emergentRoot = string(fileparts(fileparts(moduleRoot)));
    supplementaryRoot = fullfile(emergentRoot, "outputs", "supplementary");
end
eta90Thresholds = [6 5 7 8];
groupOrder = ["Pooled","Power","Water","Gas"];


scriptDir = string(fileparts(mfilename("fullpath")));
moduleRoot = scriptDir;
emergentRoot = string(fileparts(fileparts(moduleRoot)));
intermediateRoot = fullfile( ...
    emergentRoot, ...
    "outputs", ...
    "intermediate", ...
    "02_loss_compression_late_loss");

addpath(scriptDir);

inputMat = fullfile( ...
    intermediateRoot, ...
    "loss_tail_dataset.mat");

suppOutputRoot = fullfile(supplementaryRoot, "source_data");

ensureDir(suppOutputRoot);

if ~isfile(inputMat)
    error( ...
        "Prepared loss-tail MAT not found:\n%s\n" + ...
        "Run run_00_prepare_loss_tail_dataset.m first.", ...
        inputMat);
end


S = load(inputMat, "LossTailRecords");

if ~isfield(S, "LossTailRecords")
    error( ...
        "MAT file does not contain LossTailRecords:\n%s", ...
        inputMat);
end

T = normalizeLossTailTable(S.LossTailRecords);

requiredFields = [ ...
    "record_ID", ...
    "system", ...
    "nRestorationRatioPoints", ...
    "eta90", ...
    "eta95"];

assertRequiredFields( ...
    T, ...
    requiredFields, ...
    "LossTailRecords");

pointCounts = ...
    double(T.nRestorationRatioPoints);


Eta90 = table();

for ti = 1:numel(eta90Thresholds)

    threshold = ...
        eta90Thresholds(ti);

    if threshold == 6

        specification = ...
            "Baseline analysis (>=6 points)";

    else

        specification = ...
            sprintf( ...
                "Sensitivity analysis (>=%d points)", ...
                threshold);
    end

    thresholdMask = ...
        isfinite(pointCounts) & ...
        pointCounts >= threshold;

    for gi = 1:numel(groupOrder)

        group = ...
            groupOrder(gi);

        [displayRow, ~] = ...
            summarizeTailMetric( ...
                T, ...
                thresholdMask, ...
                "eta90", ...
                "eta90", ...
                string(specification), ...
                threshold, ...
                group);

        Eta90 = [ ...
            Eta90
            displayRow];
    end
end


lateLossXlsx = fullfile( ...
    suppOutputRoot, ...
    "SourceData_TableS5.xlsx");

LateLossDisplay = Eta90(:, { ...
    'Analysis_specification', ...
    'Lifeline', ...
    'n', ...
    'Median', ...
    'Q25_Q75', ...
    'Q05_Q95'});

LateLossDisplay.Properties.VariableNames = { ...
    'Analysis_specification', ...
    'Lifeline_system', ...
    'Sample_size', ...
    'Median', ...
    'Q25_Q75', ...
    'Q05_Q95'};

writeTableCompatPortable(LateLossDisplay, lateLossXlsx, "display_table");

fprintf( ...
    "Saved late-loss fraction resolution-sensitivity source data:\n%s\n", ...
    lateLossXlsx);


end

function [displayRow, sourceRow] = ...
        summarizeTailMetric( ...
            T, ...
            pointMask, ...
            metricField, ...
            metricLabel, ...
            specification, ...
            minPoints, ...
            group)

valuesAll = ...
    double(T.(char(metricField)));

mask = ...
    logical(pointMask(:)) & ...
    isfinite(valuesAll) & ...
    valuesAll >= 0;

if group ~= "Pooled"

    mask = ...
        mask & ...
        T.system == group;
end

values = ...
    valuesAll(mask);

q = quantileLocal( ...
    values, ...
    [0.05 0.25 0.50 0.75 0.95]);

lifeline = ...
    groupLabel(group);

if string(metricField) == "eta90"

    medianText = ...
        formatPercentNumber(q(3));

    q25q75Text = ...
        formatPercentInterval(q(2), q(4));

    q05q95Text = ...
        formatPercentInterval(q(1), q(5));

else

    medianText = ...
        formatNumber(q(3));

    q25q75Text = ...
        formatInterval(q(2), q(4));

    q05q95Text = ...
        formatInterval(q(1), q(5));
end

displayRow = table( ...
    string(specification), ...
    lifeline, ...
    numel(values), ...
    medianText, ...
    q25q75Text, ...
    q05q95Text, ...
    'VariableNames', { ...
        'Analysis_specification', ...
        'Lifeline', ...
        'n', ...
        'Median', ...
        'Q25_Q75', ...
        'Q05_Q95'});

sourceRow = table( ...
    string(specification), ...
    string(metricField), ...
    string(metricLabel), ...
    minPoints, ...
    group, ...
    lifeline, ...
    numel(values), ...
    q(1), ...
    q(2), ...
    q(3), ...
    q(4), ...
    q(5), ...
    'VariableNames', { ...
        'Analysis_specification', ...
        'metric', ...
        'Tail_loss_metric', ...
        'min_points', ...
        'group', ...
        'Lifeline', ...
        'n', ...
        'Q05', ...
        'Q25', ...
        'median', ...
        'Q75', ...
        'Q95'});

end

function q = quantileLocal( ...
        values, ...
        probabilities)

values = ...
    sort( ...
        double(values(:)));

values = ...
    values(isfinite(values));

q = nan(size(probabilities));

if isempty(values)
    return;
end

for i = 1:numel(probabilities)

    p = probabilities(i);

    if numel(values) == 1

        q(i) = values(1);

    else

        position = ...
            1 + ...
            (numel(values) - 1) * p;

        lowerIndex = floor(position);
        upperIndex = ceil(position);

        if lowerIndex == upperIndex

            q(i) = ...
                values(lowerIndex);

        else

            q(i) = ...
                values(lowerIndex) + ...
                (values(upperIndex) - values(lowerIndex)) * ...
                (position - lowerIndex);
        end
    end
end

end


function s = formatNumber(x)

if ~isfinite(x)

    s = "";

else

    s = string(sprintf("%.2f", x));
end

end

function s = formatPercentNumber(x)

if ~isfinite(x)

    s = "";

else

    s = string(sprintf("%.2f%%", 100 .* x));
end

end

function s = formatInterval( ...
        low, ...
        high)

if ~( ...
        isfinite(low) && ...
        isfinite(high))

    s = "";

else

    s = ...
        "[" + ...
        formatNumber(low) + ...
        "-" + ...
        formatNumber(high) + ...
        "]";
end

end

function s = formatPercentInterval( ...
        low, ...
        high)

if ~( ...
        isfinite(low) && ...
        isfinite(high))

    s = "";

else

    s = ...
        "[" + ...
        formatPercentNumber(low) + ...
        "-" + ...
        formatPercentNumber(high) + ...
        "]";
end

end

function T = normalizeLossTailTable(T)

if ~istable(T)
    error("LossTailRecords must be a table.");
end

vars = string(T.Properties.VariableNames);

if ismember("System", vars)

    T.system = ...
        normalizeSystemName(T.System);

elseif ismember("system", vars)

    T.system = ...
        normalizeSystemName(T.system);

else

    error( ...
        "LossTailRecords must contain System or system.");
end

if ismember("record_ID", string(T.Properties.VariableNames))

    T.record_ID = ...
        string(T.record_ID);
end

end
function assertRequiredFields( ...
        T, ...
        requiredFields, ...
        label)

available = ...
    string(T.Properties.VariableNames);

missing = ...
    requiredFields( ...
        ~ismember(requiredFields, available));

if ~isempty(missing)

    error( ...
        "%s is missing required field(s): %s", ...
        label, ...
        strjoin(missing, ", "));
end

end

function s = normalizeSystemName(s)

s = string(s);
sl = lower(strtrim(s));

s( ...
    sl == "e" | ...
        sl == "power") = ...
    "Power";

s( ...
    sl == "w" | ...
    sl == "water" | ...
    sl == "water supply") = ...
    "Water";

s( ...
    sl == "g" | ...
    sl == "gas" | ...
    sl == "natural gas") = ...
    "Gas";

end

function g = groupLabel(g)

if g == "Pooled"

    g = "All";

elseif g == "Power"

    g = "Electric power";

elseif g == "Water"

    g = "Water supply";

elseif g == "Gas"

    g = "Natural gas";
end

end

function ensureDir(directoryPath)

if exist(directoryPath, "dir") ~= 7
    mkdir(directoryPath);
end

end
