
function make_TableS7_Cmax_summary(supplementaryRoot)

if nargin < 1 || isempty(supplementaryRoot)
    scriptDir = string(fileparts(mfilename("fullpath")));
    moduleRoot = scriptDir;
    emergentRoot = string(fileparts(fileparts(moduleRoot)));
    supplementaryRoot = fullfile(emergentRoot, "outputs", "supplementary");
end

scriptDir = string(fileparts(mfilename("fullpath")));
moduleRoot = scriptDir;
emergentRoot = string(fileparts(fileparts(moduleRoot)));
intermediateRoot = fullfile( ...
    emergentRoot, ...
    "outputs", ...
    "intermediate", ...
    "03_cross_lifeline_timing_coupling");

addpath(scriptDir);

inputMat = fullfile( ...
    intermediateRoot, ...
    "paired_timing_coupling_dataset.mat");

outputDir = fullfile(supplementaryRoot, "source_data");

outXlsx = fullfile( ...
    outputDir, ...
    "SourceData_TableS7.xlsx");

ensureDir(outputDir);

if ~isfile(inputMat)
    error( ...
        "Paired timing/coupling MAT not found:\n%s\n" + ...
        "Run run_01_make_cross_lifeline_timing_coupling_source_data.m first.", ...
        inputMat);
end


S = load( ...
    inputMat, ...
    "Paired");

if ~isfield(S, "Paired")
    error( ...
        "MAT file does not contain Paired:\n%s", ...
        inputMat);
end

T = normalizePairedTable(S.Paired);

if isempty(T)
    error( ...
        "Paired dataset is empty:\n%s", ...
        inputMat);
end

requiredFields = [ ...
    "systemPair", ...
    "CmaxAB90", ...
    "CmaxAB95", ...
    "CmaxAB100"];

assertRequiredFields( ...
    T, ...
    requiredFields, ...
    "Paired");


pValue = [ ...
    90
    90
    95
    95
    100
    100];

pairType = [ ...
    "EW"
    "EG"
    "EW"
    "EG"
    "EW"
    "EG"];

nRows = ...
    numel(pValue);


System_pair = strings(nRows, 1);
p = nan(nRows, 1);
pair = strings(nRows, 1);
pairTypeOut = strings(nRows, 1);

Records_n = zeros(nRows, 1);
Fraction_below_5pct = nan(nRows, 1);
Fraction_below_10pct = nan(nRows, 1);

for i = 1:nRows

    thisP = ...
        pValue(i);

    thisPairType = ...
        pairType(i);

    fieldName = ...
        "CmaxAB" + ...
        string(thisP);

    allValues = ...
        double(T.(char(fieldName)));

    pairMask = T.systemPair == thisPairType;
    finiteMask = pairMask & isfinite(allValues);

    if any(allValues(finiteMask) < -1e-12)
        error("%s contains negative finite values for %s.", ...
            fieldName, thisPairType);
    end

    mask = finiteMask;

    values = ...
        allValues(mask);

    n = ...
        numel(values);

    if thisPairType == "EW"

        pairLabel = ...
            "E->W";

    elseif thisPairType == "EG"

        pairLabel = ...
            "E->G";

    else

        error( ...
            "Unsupported pair type: %s", ...
            thisPairType);
    end

    systemPairLabel = ...
        "Cmax_" + ...
        pairLabel + ...
        "(" + ...
        string(thisP) + ...
        ")";

    System_pair(i) = ...
        systemPairLabel;

    p(i) = ...
        thisP;

    pair(i) = ...
        pairLabel;

    pairTypeOut(i) = ...
        thisPairType;

    Records_n(i) = ...
        n;

    Fraction_below_5pct(i) = ...
        safeFraction( ...
            nnz(values <= 0.05), ...
            n);

    Fraction_below_10pct(i) = ...
        safeFraction( ...
            nnz(values <= 0.10), ...
            n);
end

NumericTable = table( ...
    System_pair, ...
    p, ...
    pair, ...
    pairTypeOut, ...
    Records_n, ...
    Fraction_below_5pct, ...
    Fraction_below_10pct, ...
    'VariableNames', { ...
        'System_pair', ...
        'p', ...
        'pair', ...
        'pairType', ...
        'Records_n', ...
        'Fraction_below_5pct', ...
        'Fraction_below_10pct'});


DisplayFraction5 = strings(nRows, 1);
DisplayFraction10 = strings(nRows, 1);

for i = 1:nRows

    DisplayFraction5(i) = ...
        formatFraction( ...
            NumericTable.Fraction_below_5pct(i));

    DisplayFraction10(i) = ...
        formatFraction( ...
            NumericTable.Fraction_below_10pct(i));
end

DisplayTable = table( ...
    NumericTable.System_pair, ...
    NumericTable.Records_n, ...
    DisplayFraction5, ...
    DisplayFraction10, ...
    'VariableNames', { ...
        'System_pair', ...
        'Records_n', ...
        'Fraction_below_5pct', ...
        'Fraction_below_10pct'});

if isfile(outXlsx)
    delete(outXlsx);
end

writeTableCompatPortable( ...
    DisplayTable, ...
    outXlsx, ...
    "display_table");

writeTableCompatPortable( ...
    NumericTable, ...
    outXlsx, ...
    "numeric_source");

fprintf( ...
    "Saved supplementary Cmax summary table:\n%s\n", ...
    outXlsx);



end

function T = normalizePairedTable(T)

if ~istable(T)
    error("Paired must be a table.");
end

if ~ismember( ...
        "systemPair", ...
        string(T.Properties.VariableNames))

    error("Paired must contain systemPair.");
end

T.systemPair = ...
    upper( ...
        strtrim( ...
            string(T.systemPair)));

end

function assertRequiredFields( ...
        T, ...
        requiredFields, ...
        label)

available = ...
    string(T.Properties.VariableNames);

missing = ...
    requiredFields( ...
        ~ismember(requiredFields, available));

if ~isempty(missing)

    error( ...
        "%s is missing required field(s): %s", ...
        label, ...
        strjoin(missing, ", "));
end

end

function value = safeFraction( ...
        numerator, ...
        denominator)

if denominator > 0

    value = ...
        numerator ./ denominator;

else

    value = NaN;
end

end

function textValue = formatFraction(value)

if ~isfinite(value)

    textValue = "";

else

    textValue = ...
        string( ...
            sprintf( ...
                "%.3f", ...
                value));
end

end

function ensureDir(directoryPath)

if exist(char(directoryPath), 'dir') ~= 7
    mkdir(char(directoryPath));
end

end
