
function make_TableS3_successive_milestone_ratio_resolution_sensitivity(supplementaryRoot)

if nargin < 1 || isempty(supplementaryRoot)
    scriptDir = string(fileparts(mfilename("fullpath")));
    moduleRoot = scriptDir;
    emergentRoot = string(fileparts(fileparts(moduleRoot)));
    supplementaryRoot = fullfile(emergentRoot, "outputs", "supplementary");
end

scriptDir = string(fileparts(mfilename("fullpath")));
moduleRoot = scriptDir;
emergentRoot = string(fileparts(fileparts(moduleRoot)));
intermediateRoot = fullfile( ...
    emergentRoot, ...
    "outputs", ...
    "intermediate", ...
    "01_restoration_shape_phase_ratio");

inputMat = fullfile( ...
    intermediateRoot, ...
    "unique3_records.mat");

suppOutputRoot = supplementaryRoot;

sourceDataDir = fullfile( ...
    suppOutputRoot, ...
    "source_data");

ensureDir(sourceDataDir);

sourceXlsx = fullfile( ...
    sourceDataDir, ...
    "SourceData_TableS3.xlsx");

if ~isfile(inputMat)

    error( ...
        "Prepared dataset not found:\n%s\n" + ...
        "Run run_00_prepare_well_resolved_curves.m first.", ...
        inputMat);
end


S = load( ...
    inputMat, ...
    "unique3Records");

if ~isfield(S, "unique3Records")

    error( ...
        "MAT file does not contain unique3Records:\n%s", ...
        inputMat);
end

records = S.unique3Records;

if isempty(records)

    error( ...
        "unique3Records is empty:\n%s", ...
        inputMat);
end

requiredFields = [ ...
    "record_ID", ...
    "System", ...
    "nRestorationRatioPoints", ...
    "nUniqueRestorationValues", ...
    "tau80_over_tau50", ...
    "tau90_over_tau80", ...
    "tau95_over_tau90"];

availableFields = string(fieldnames(records));

missingFields = requiredFields( ...
    ~ismember(requiredFields, availableFields));

if ~isempty(missingFields)

    error( ...
        "unique3Records is missing required field(s): %s", ...
        strjoin(missingFields, ", "));
end

Ratio = ratioTableFromRecords(records);


systemKeys = [ ...
    "Pooled", ...
    "Power", ...
    "Water", ...
    "Gas"];

lifelineLabels = [ ...
    "All", ...
    "Electric power", ...
    "Water supply", ...
    "Natural gas"];

metricFields = [ ...
    "tau80_over_tau50", ...
    "tau90_over_tau80", ...
    "tau95_over_tau90"];

metricLabels = [ ...
    "\tau_{80}/\tau_{50}", ...
    "\tau_{90}/\tau_{80}", ...
    "\tau_{95}/\tau_{90}"];

cohortNames = [ ...
    "Baseline_ge6", ...
    "Sensitivity_ge5", ...
    "Sensitivity_ge7", ...
    "Sensitivity_ge8", ...
    "Expanded_unique3"];

cohortLabels = [ ...
    ">=6 points (baseline)", ...
    ">=5 points", ...
    ">=7 points", ...
    ">=8 points", ...
    ">=3 points"];

pointThresholds = [6, 5, 7, 8, NaN];


nRows = numel(systemKeys) * numel(metricFields);

Lifeline = strings(nRows, 1);
Phase_ratio = strings(nRows, 1);

Baseline_ge6 = strings(nRows, 1);
Sensitivity_ge5 = strings(nRows, 1);
Sensitivity_ge7 = strings(nRows, 1);
Sensitivity_ge8 = strings(nRows, 1);
Expanded_unique3 = strings(nRows, 1);

summaryRows = cell(0, 1);

rowIndex = 0;

for s = 1:numel(systemKeys)

    for m = 1:numel(metricFields)

        rowIndex = rowIndex + 1;

        Lifeline(rowIndex) = lifelineLabels(s);
        Phase_ratio(rowIndex) = metricLabels(m);

        ranges = strings(1, numel(cohortNames));

        for c = 1:numel(cohortNames)

            [n, q05, q25, q50, q75, q95] = summarizeCohort( ...
                Ratio, ...
                systemKeys(s), ...
                metricFields(m), ...
                pointThresholds(c));

            ranges(c) = formatSummary(n, q05, q25, q50, q75, q95);

            summaryRows{end + 1, 1} = table( ...
                lifelineLabels(s), ...
                lifelineLabels(s), ...
                metricLabels(m), ...
                metricFields(m), ...
                cohortNames(c), ...
                cohortLabels(c), ...
                pointThresholds(c), ...
                n, ...
                q05, ...
                q25, ...
                q50, ...
                q75, ...
                q95, ...
                ranges(c), ...
                'VariableNames', { ...
                    'Lifeline', ...
                    'System', ...
                    'Phase_ratio', ...
                    'metric_field', ...
                    'cohort', ...
                    'cohort_definition', ...
                    'minimum_points', ...
                    'n', ...
                    'Q05', ...
                    'Q25', ...
                    'Median', ...
                    'Q75', ...
                    'Q95', ...
                    'display_value'});
        end

        Baseline_ge6(rowIndex) = ranges(1);
        Sensitivity_ge5(rowIndex) = ranges(2);
        Sensitivity_ge7(rowIndex) = ranges(3);
        Sensitivity_ge8(rowIndex) = ranges(4);
        Expanded_unique3(rowIndex) = ranges(5);
    end
end

TableS3 = table( ...
    Lifeline, ...
    Phase_ratio, ...
    Baseline_ge6, ...
    Sensitivity_ge5, ...
    Sensitivity_ge7, ...
    Sensitivity_ge8, ...
    Expanded_unique3);

SummaryLong = vertcat(summaryRows{:});
SummaryLong = roundSummaryColumns(SummaryLong);

TableS3Cell = [
    {"Lifeline system", ...
     "Successive milestone ratio", ...
     ">=6 points (baseline)", ...
     ">=5 points", ...
     ">=7 points", ...
     ">=8 points", ...
     ">=3 points"}
    cellstr(TableS3.Lifeline), ...
    cellstr(TableS3.Phase_ratio), ...
    cellstr(TableS3.Baseline_ge6), ...
    cellstr(TableS3.Sensitivity_ge5), ...
    cellstr(TableS3.Sensitivity_ge7), ...
    cellstr(TableS3.Sensitivity_ge8), ...
    cellstr(TableS3.Expanded_unique3)];


if isfile(sourceXlsx)
    delete(sourceXlsx);
end

writecell( ...
    TableS3Cell, ...
    sourceXlsx, ...
    "Sheet", ...
    "display_table");

writeTablePortable( ...
    SummaryLong, ...
    sourceXlsx, ...
    "summary_long");

writeTablePortable( ...
    Ratio, ...
    sourceXlsx, ...
    "record_level");

fprintf( ...
    "Saved Table S3 source data:\n%s\n", ...
    sourceXlsx);


end

function T = ratioTableFromRecords(records)

n = numel(records);

record_ID = strings(n, 1);
System = strings(n, 1);

nRestorationRatioPoints = nan(n, 1);
nUniqueRestorationValues = nan(n, 1);

tau80_over_tau50 = nan(n, 1);
tau90_over_tau80 = nan(n, 1);
tau95_over_tau90 = nan(n, 1);

for i = 1:n

    rec = records(i);

    record_ID(i) = ...
        getStringField(rec, "record_ID");

    System(i) = ...
        canonicalSystemName( ...
            getStringField(rec, "System"));

    nRestorationRatioPoints(i) = ...
        getNumericField(rec, "nRestorationRatioPoints");

    nUniqueRestorationValues(i) = ...
        getNumericField(rec, "nUniqueRestorationValues");

    tau80_over_tau50(i) = ...
        getNumericField(rec, "tau80_over_tau50");

    tau90_over_tau80(i) = ...
        getNumericField(rec, "tau90_over_tau80");

    tau95_over_tau90(i) = ...
        getNumericField(rec, "tau95_over_tau90");
end

T = table( ...
    record_ID, ...
    System, ...
    nRestorationRatioPoints, ...
    nUniqueRestorationValues, ...
    tau80_over_tau50, ...
    tau90_over_tau80, ...
    tau95_over_tau90);

end


function [n, q05, q25, q50, q75, q95] = summarizeCohort( ...
        T, ...
        systemName, ...
        metricField, ...
        minimumPoints)

valuesAll = double(T.(char(metricField)));

mask = ...
    T.nUniqueRestorationValues >= 3 & ...
    isfinite(valuesAll);

if systemName ~= "Pooled"

    mask = ...
        mask & ...
        T.System == systemName;
end

if isfinite(minimumPoints)

    mask = ...
        mask & ...
        T.nRestorationRatioPoints >= minimumPoints;
end

values = valuesAll(mask);
values = double(values(:));
values = values(isfinite(values));

n = numel(values);

q05 = NaN;
q25 = NaN;
q50 = NaN;
q75 = NaN;
q95 = NaN;

if n > 0

    q = quantile( ...
        values, ...
        [0.05, 0.25, 0.50, 0.75, 0.95]);

    q05 = q(1);
    q25 = q(2);
    q50 = q(3);
    q75 = q(4);
    q95 = q(5);
end

end

function txt = formatSummary(n, q05, q25, q50, q75, q95)

if ~(isfinite(q05) && isfinite(q25) && isfinite(q50) && ...
        isfinite(q75) && isfinite(q95))

    txt = string(sprintf("(%d)", n));
    return;
end

txt = string(sprintf( ...
    "%.3f [%.3f-%.3f; %.3f-%.3f]\n(%d)", ...
    q50, ...
    q25, ...
    q75, ...
    q05, ...
    q95, ...
    n));

end


function T = roundSummaryColumns(T)

cols = ["Q05", "Q25", "Median", "Q75", "Q95"];
for i = 1:numel(cols)
    if ismember(cols(i), string(T.Properties.VariableNames))
        T.(cols(i)) = round(double(T.(cols(i))), 3);
    end
end

end

function sys = canonicalSystemName(x)

x = lower(strtrim(string(x)));

sys = strings(size(x));

for i = 1:numel(x)

    switch x(i)

        case {"e", "power"}

            sys(i) = "Power";

        case {"w", "water", "water supply"}

            sys(i) = "Water";

        case {"g", "gas", "natural gas"}

            sys(i) = "Gas";

        otherwise

            sys(i) = string(x(i));
    end
end

end

function x = getNumericField(S, fieldName)

x = NaN;

if ~isstruct(S) || ...
        ~isfield(S, fieldName) || ...
        isempty(S.(fieldName))

    return;
end

v = S.(fieldName);

if isnumeric(v) || islogical(v)

    if isscalar(v) && isfinite(double(v))
        x = double(v);
    end

elseif isstring(v) || ischar(v)

    y = str2double(string(v));

    if isscalar(y) && isfinite(y)
        x = y;
    end
end

end

function s = getStringField(S, fieldName)

s = "";

if ~isstruct(S) || ...
        ~isfield(S, fieldName) || ...
        isempty(S.(fieldName))

    return;
end

v = S.(fieldName);

if isstring(v)

    v(ismissing(v)) = "";
    s = string(v);

    if numel(s) > 1
        s = strjoin(s(:).', " ");
    end

elseif ischar(v)

    s = string(v);

elseif isnumeric(v) || islogical(v)

    if isscalar(v) && isfinite(double(v))
        s = string(v);
    end
end

s = strtrim(s);

end

function writeTablePortable(T, filename, varargin)

filename = string(filename);

if exist("writeTableCompatPortable", "file") == 2

    writeTableCompatPortable( ...
        T, ...
        filename, ...
        varargin{:});

    return;
end

if isempty(varargin)

    writetable( ...
        T, ...
        filename);

else

    sheetName = varargin{1};

    writetable( ...
        T, ...
        filename, ...
        "Sheet", ...
        char(sheetName));
end

end

function ensureDir(p)

if exist(p, "dir") ~= 7
    mkdir(p);
end

end
