
function plot_FigS7_curve_resolution_sensitivity(supplementaryRoot, figureDataRoot)

if nargin < 1 || isempty(supplementaryRoot)
    scriptDir = string(fileparts(mfilename("fullpath")));
    moduleRoot = scriptDir;
    emergentRoot = string(fileparts(fileparts(moduleRoot)));
    supplementaryRoot = fullfile(emergentRoot, "outputs", "supplementary");
end
if nargin >= 2 && strlength(string(figureDataRoot)) > 0
    renderFigS7FromSourceData(supplementaryRoot, figureDataRoot);
    return;
end

scriptDir = string(fileparts(mfilename("fullpath")));
moduleRoot = scriptDir;
emergentRoot = string(fileparts(fileparts(moduleRoot)));
intermediateRoot = fullfile( ...
    emergentRoot, ...
    "outputs", ...
    "intermediate", ...
    "01_restoration_shape_phase_ratio");

addpath(scriptDir);

fitMat = fullfile( ...
    intermediateRoot, ...
    "restoration_shape_ge5_fit_result.mat");

suppOutputRoot = supplementaryRoot;

figureDir = fullfile(suppOutputRoot, "figures");
sourceDataDir = fullfile(suppOutputRoot, "source_data");

ensureDir(figureDir);
ensureDir(sourceDataDir);

outBase = fullfile( ...
    figureDir, ...
    "FigS7_curve_resolution_sensitivity");


sourceXlsx = fullfile( ...
    sourceDataDir, ...
    "SourceData_FigS7.xlsx");

if ~isfile(fitMat)
    error( ...
        "Curve summary not found:\n%s\n" + ...
        "Run run_01_fit_restoration_shape_models.m first.", ...
        fitMat);
end


F = load(fitMat, "fitResult");

if ~isfield(F, "fitResult") || ...
        ~isfield(F.fitResult, "CurveSummary") || ...
        ~isfield(F.fitResult, "CurveFitParams")
    error("MAT file does not contain required fitResult tables:\n%s", fitMat);
end

CS = F.fitResult.CurveSummary;
FP = F.fitResult.CurveFitParams;

CS = normalizeStrings(CS);
FP = normalizeStrings(FP);

requiredCS = [ ...
    "record_ID", ...
    "System", ...
    "sys", ...
    "n_points", ...
    "bestModel"];

requiredFP = [ ...
    "record_ID", ...
    "System", ...
    "sys", ...
    "n_points", ...
    "model", ...
    "MAE"];

assertRequiredColumns(CS, requiredCS, "curve summary");
assertRequiredColumns(FP, requiredFP, "curve-fit parameter table");

CS.System = canonicalSystemName(CS.System);
FP.System = canonicalSystemName(FP.System);


thresholds = [6, 5, 7, 8];
thresholdLabels = [ ...
    "\geq6 points", ...
    "\geq5 points", ...
    "\geq7 points", ...
    "\geq8 points"];

systemGroups = ["Power", "Water", "Gas"];
systemCodes = ["E", "W", "G"];
systemNames = ["Electric power", "Water supply", "Natural gas"];

models = [ ...
    "Weibull", ...
    "Gompertz", ...
    "Log-logistic", ...
    "Exponential", ...
    "Mechanical analogy", ...
    "Opabola", ...
    "Zorn", ...
    "Trigonometric"];

systemColors = [ ...
    0.70 0.14 0.16
    0.17 0.46 0.72
    0.78 0.55 0.18];

maeThreshold = 0.05;


sourceRows = cell(0, 1);

fig = figure( ...
    "Color", "w", ...
    "Units", "pixels", ...
    "Position", [70 30 1650 1850], ...
    "Visible", "off", ...
    "Resize", "off");

set( ...
    fig, ...
    "DefaultAxesFontName", "Arial", ...
    "DefaultTextFontName", "Arial");

tl = tiledlayout( ...
    fig, ...
    numel(thresholds), ...
    1, ...
    "TileSpacing", "loose", ...
    "Padding", "loose");

legendHandles = gobjects(0);

for ti = 1:numel(thresholds)

    threshold = thresholds(ti);

    [winnerRate, maeShare, nEligible] = ...
        summarizeThreshold( ...
            CS, ...
            FP, ...
            threshold, ...
            systemGroups, ...
            models, ...
            maeThreshold);

    showXLabels = ...
        (ti == numel(thresholds));

    ax = nexttile(tl);
    hold(ax, "on");

    legendHandles = drawModelSelectionSingleAxis( ...
        ax, ...
        winnerRate, ...
        maeShare, ...
        nEligible, ...
        systemCodes, ...
        systemNames, ...
        models, ...
        systemColors, ...
        showXLabels, ...
        legendHandles);

    title( ...
        ax, ...
        thresholdLabels(ti), ...
        "FontWeight", "bold", ...
        "FontSize", 19, ...
        "Interpreter", "tex");

    text( ...
        ax, ...
        -0.010, ...
        1.045, ...
        char('a' + ti - 1), ...
        "Units", "normalized", ...
        "FontWeight", "bold", ...
        "FontSize", 17, ...
        "Clipping", "off");

    for s = 1:numel(systemGroups)

        for m = 1:numel(models)

            sourceRows{end + 1, 1} = table( ...
                threshold, ...
                systemNames(s), ...
                systemCodes(s), ...
                models(m), ...
                nEligible(s), ...
                winnerRate(s, m), ...
                maeShare(s, m), ...
                'VariableNames', { ...
                    'min_points', ...
                    'system', ...
                    'system_code', ...
                    'model', ...
                    'nEligible', ...
                    'winnerRate', ...
                    'shareMAE_le_0p05'});
        end
    end
end

if numel(legendHandles) >= 2 && ...
        all(isgraphics(legendHandles(1:2)))

    lgd = legend( ...
        legendHandles(1:2), ...
        ["Best fit (AICc)", ...
         "Adequate fit (MAE \leq 0.05)"], ...
        "Orientation", "horizontal", ...
        "Box", "off", ...
        "FontSize", 19, ...
        "FontName", "Arial", ...
        "Interpreter", "tex");

    try

        lgd.Layout.Tile = "north";

    catch

        lgd.Location = "northoutside";
    end
end

SourceData = vertcat(sourceRows{:});

if isfile(sourceXlsx)
    delete(sourceXlsx);
end

writeTableCompatPortable( ...
    SourceData, ...
    sourceXlsx, ...
    "FigS7_source_data");

finishFigure(fig, outBase, 300);
close(fig);

fprintf( ...
    "Saved Fig S7 outputs (>=6-point panel first) under:\n%s\n", ...
    suppOutputRoot);


end

function renderFigS7FromSourceData(figureDir, figureDataRoot)

sourceXlsx = fullfile(figureDataRoot, "SourceData_FigS7.xlsx");
if ~isfile(sourceXlsx)
    error("Frozen Figure S7 source workbook not found: %s", sourceXlsx);
end
ensureDir(figureDir);

S = readtable(sourceXlsx, "Sheet", "FigS7_source_data", ...
    "TextType", "string", "VariableNamingRule", "preserve");
required = ["min_points", "system", "system_code", "model", ...
    "nEligible", "winnerRate", "shareMAE_le_0p05"];
assertRequiredColumns(S, required, "frozen Figure S7 source data");
S = normalizeStrings(S);

thresholds = [6, 5, 7, 8];
thresholdLabels = ["\geq6 points", "\geq5 points", "\geq7 points", "\geq8 points"];
systemGroups = ["Power", "Water", "Gas"];
systemCodes = ["E", "W", "G"];
systemNames = ["Electric power", "Water supply", "Natural gas"];
models = ["Weibull", "Gompertz", "Log-logistic", "Exponential", ...
    "Mechanical analogy", "Opabola", "Zorn", "Trigonometric"];
systemColors = [0.70 0.14 0.16; 0.17 0.46 0.72; 0.78 0.55 0.18];

fig = figure("Color", "w", "Units", "pixels", ...
    "Position", [70 30 1650 1850], "Visible", "off", "Resize", "off");
set(fig, "DefaultAxesFontName", "Arial", "DefaultTextFontName", "Arial");
tl = tiledlayout(fig, numel(thresholds), 1, "TileSpacing", "loose", "Padding", "loose");
legendHandles = gobjects(0);

for ti = 1:numel(thresholds)
    [winnerRate, maeShare, nEligible] = summarizeFrozenSource( ...
        S, thresholds(ti), systemNames, models);
    ax = nexttile(tl);
    hold(ax, "on");
    legendHandles = drawModelSelectionSingleAxis(ax, winnerRate, maeShare, ...
        nEligible, systemCodes, systemNames, models, systemColors, ...
        ti == numel(thresholds), legendHandles);
    title(ax, thresholdLabels(ti), "FontWeight", "bold", ...
        "FontSize", 19, "Interpreter", "tex");
    text(ax, -0.010, 1.045, char('a' + ti - 1), "Units", "normalized", ...
        "FontWeight", "bold", "FontSize", 17, "Clipping", "off");
end

if numel(legendHandles) >= 2 && all(isgraphics(legendHandles(1:2)))
    lgd = legend(legendHandles(1:2), ["Best fit (AICc)", ...
        "Adequate fit (MAE \leq 0.05)"], "Orientation", "horizontal", ...
        "Box", "off", "FontSize", 19, "FontName", "Arial", "Interpreter", "tex");
    try
        lgd.Layout.Tile = "north";
    catch
        lgd.Location = "northoutside";
    end
end

finishFigure(fig, fullfile(figureDir, "FigS7_curve_resolution_sensitivity"), 300);
close(fig);
fprintf("Saved Fig S7 from frozen figure data under:\n%s\n", figureDir);

end

function [winnerRate, maeShare, nEligible] = summarizeFrozenSource(S, threshold, systemNames, models)

winnerRate = nan(numel(systemNames), numel(models));
maeShare = nan(numel(systemNames), numel(models));
nEligible = nan(numel(systemNames), 1);
for s = 1:numel(systemNames)
    for m = 1:numel(models)
        row = double(S.min_points) == threshold & ...
            string(S.system) == systemNames(s) & string(S.model) == models(m);
        if nnz(row) ~= 1
            error("Frozen Figure S7 source data have %d rows for %s, %s, minimum %d points.", ...
                nnz(row), systemNames(s), models(m), threshold);
        end
        winnerRate(s, m) = double(S.winnerRate(row));
        maeShare(s, m) = double(S.shareMAE_le_0p05(row));
        nEligible(s) = double(S.nEligible(row));
    end
end

end

function [winnerRate, maeShare, nEligible] = summarizeThreshold( ...
        CS, ...
        FP, ...
        minPoints, ...
        systemGroups, ...
        models, ...
        maeThreshold)

winnerRate = nan(numel(systemGroups), numel(models));
maeShare = nan(numel(systemGroups), numel(models));
nEligible = zeros(numel(systemGroups), 1);

eligibleMask = ...
    CS.n_points >= minPoints & ...
    ~startsWith(string(CS.bestModel), "skipped:");

Eligible = CS(eligibleMask, :);

for s = 1:numel(systemGroups)

    G = Eligible(Eligible.System == systemGroups(s), :);

    ids = unique(string(G.record_ID), "stable");
    ids = ids(strlength(ids) > 0);

    nEligible(s) = numel(ids);

    for m = 1:numel(models)

        modelName = models(m);

        if nEligible(s) > 0

            winnerCount = nnz( ...
                string(G.bestModel) == modelName);

            winnerRate(s, m) = ...
                winnerCount / nEligible(s);
        end

        F = FP( ...
            ismember(string(FP.record_ID), ids) & ...
            string(FP.model) == modelName, ...
            :);

        finiteMae = isfinite(F.MAE);

        if nEligible(s) > 0

            maeShare(s, m) = ...
                nnz(finiteMae & F.MAE <= maeThreshold) / ...
                nEligible(s);
        end
    end
end

end


function legendHandles = drawModelSelectionSingleAxis( ...
        ax, ...
        winnerRate, ...
        maeShare, ...
        nEligible, ...
        systemCodes, ...
        systemNames, ...
        modelNames, ...
        systemColors, ...
        showXLabels, ...
        legendHandles)

x = 1:numel(modelNames);

groupGap = 1.15;
groupSpan = numel(modelNames) + groupGap;

barWidth = 0.56;
adequateBarWidth = barWidth;
winnerBarWidth = barWidth;

hold(ax, "on");

for s = 1:numel(systemCodes)

    xs = x + ...
        (s - 1) * groupSpan;

    systemColor = systemColors(s, :);

    for m = 1:numel(modelNames)

        if isfinite(maeShare(s, m))

            bar( ...
                ax, ...
                xs(m), ...
                maeShare(s, m), ...
                adequateBarWidth, ...
                "FaceColor", systemColor, ...
                "EdgeColor", "none", ...
                "FaceAlpha", 0.24, ...
                "HandleVisibility", "off");
        end
    end

    for m = 1:numel(modelNames)

        if isfinite(winnerRate(s, m))

            bar( ...
                ax, ...
                xs(m), ...
                winnerRate(s, m), ...
                winnerBarWidth, ...
                "FaceColor", systemColor, ...
                "EdgeColor", "none", ...
                "FaceAlpha", 0.96, ...
                "HandleVisibility", "off");
        end
    end

    text( ...
        ax, ...
        mean(xs), ...
        1.045, ...
        sprintf( ...
            "%s  {\\it n}_{\\it%s} = %d", ...
            systemNames(s), ...
            systemCodes(s), ...
            nEligible(s)), ...
        "HorizontalAlignment", "center", ...
        "VerticalAlignment", "middle", ...
        "FontSize", 19, ...
        "FontWeight", "normal", ...
        "FontName", "Arial", ...
        "Interpreter", "tex", ...
        "Color", [0.10 0.10 0.10], ...
        "Clipping", "off");
end

if isempty(legendHandles)

    hBest = patch( ...
        ax, ...
        NaN, ...
        NaN, ...
        [0.35 0.35 0.35], ...
        "FaceAlpha", 0.96, ...
        "EdgeColor", "none");

    hAdequate = patch( ...
        ax, ...
        NaN, ...
        NaN, ...
        [0.35 0.35 0.35], ...
        "FaceAlpha", 0.24, ...
        "EdgeColor", "none");

    legendHandles = [ ...
        hBest; ...
        hAdequate];
end

allTicks = [];
allLabels = strings(0, 1);

for s = 1:numel(systemCodes)

    allTicks = [ ...
        allTicks, ...
        x + (s - 1) * groupSpan];

    allLabels = [ ...
        allLabels; ...
        modelNames(:)];
end

set( ...
    ax, ...
    "XTick", allTicks, ...
    "TickLabelInterpreter", "none", ...
    "FontSize", 12.6, ...
    "TickLength", [0 0]);

if showXLabels

    set( ...
        ax, ...
        "XTickLabel", ...
        allLabels);

    xtickangle(ax, 45);

else

    set( ...
        ax, ...
        "XTickLabel", ...
        strings(size(allTicks)));
end

ylabel( ...
    ax, ...
    "Fraction of trajectories", ...
    "FontSize", 16.5);

ylim(ax, [0 1.10]);

xlim( ...
    ax, ...
    [0.25, max(allTicks) + 0.75]);

for s = 1:(numel(systemCodes) - 1)

    xSeparator = ...
        s * groupSpan - 0.58;

    plot( ...
        ax, ...
        [xSeparator xSeparator], ...
        [0 1.02], ...
        "-", ...
        "Color", [0.80 0.80 0.80], ...
        "LineWidth", 0.9, ...
        "HandleVisibility", "off");
end

box(ax, "off");
grid(ax, "off");

end


function T = normalizeStrings(T)

for i = 1:numel(T.Properties.VariableNames)

    name = T.Properties.VariableNames{i};
    v = T.(name);

    if iscellstr(v) || ischar(v) || isstring(v)
        T.(name) = strtrim(string(v));
    end
end

end

function assertRequiredColumns(T, required, label)

available = string(T.Properties.VariableNames);

missing = required(~ismember(required, available));

if ~isempty(missing)

    error( ...
        "%s is missing required column(s): %s", ...
        label, ...
        strjoin(missing, ", "));
end

end

function sys = canonicalSystemName(x)

x = lower(strtrim(string(x)));
sys = strings(size(x));

for i = 1:numel(x)

    switch x(i)

        case {"e", "power"}

            sys(i) = "Power";

        case {"w", "water"}

            sys(i) = "Water";

        case {"g", "gas"}

            sys(i) = "Gas";

        otherwise

            sys(i) = string(x(i));
    end
end

end

function finishFigure(fig, outBase, resolution)

set( ...
    findall(fig, "Type", "axes"), ...
    "FontName", "Arial", ...
    "LineWidth", 0.8, ...
    "Layer", "top");

set( ...
    findall(fig, "Type", "text"), ...
    "FontName", "Arial");

set(findall(fig, "-property", "FontName"), "FontName", "Arial");
set(findall(fig, "-property", "FontSize"), "FontSize", 19);

set(fig, "Visible", "on");
drawnow;

saveas(fig, char(outBase + ".fig"), "fig");

exportgraphics( ...
    fig, ...
    char(outBase + ".png"), ...
    "Resolution", resolution);

try

    exportgraphics( ...
        fig, ...
        char(outBase + ".pdf"), ...
        "ContentType", "vector");

catch

    print( ...
        fig, ...
        char(outBase + ".pdf"), ...
        "-dpdf", ...
        "-painters");
end

end

function ensureDir(p)

if exist(p, "dir") ~= 7
    mkdir(p);
end

end
