function [net,attrs,realized] = make_layered_network( ...
        specification,seedID,generatorCfg,randomBlockID)

dependencyLogic=map_dependency_logic(specification.dependencyMode);
caseRow=table(specification.N,specification.maximumDepth, ...
    {specification.taskLayerProfile},specification.taskCountConcentration, ...
    {dependencyLogic},specification.parentConcentration, ...
    {specification.serviceLayerProfile},specification.durationDepthRatio, ...
    specification.CVd,specification.CVw,specification.rhoDW,randomBlockID, ...
    'VariableNames',{'nTasks','maximumDepth','taskLayerProfile', ...
    'taskCountConcentration','dependencyLogic','parentConcentration', ...
    'serviceLayerProfile','durationDepthRatio','cvDurationWithinLayer', ...
    'cvWeightWithinLayer','rhoDurationWeight','randomBlockID'});

[sourceNet,realized]=af_generate_repair_task_network( ...
    caseRow,seedID,generatorCfg);
net=adapt_network(sourceNet);
attrs=struct('duration',sourceNet.duration,'weight',sourceNet.weight, ...
    'CVdRealized',realized.cvDurationWithinLayer, ...
    'CVwRealized',realized.cvWeightWithinLayer, ...
    'rhoDWRealized',realized.rhoDurationWeight);
end

function logic=map_dependency_logic(mode)
switch lower(mode)
    case 'single_parent', logic='single';
    case 'two_mandatory_parents', logic='and2';
    case 'two_alternative_parents', logic='or2';
    otherwise, error('Unknown coupled dependency mode: %s',mode);
end
end

function net=adapt_network(source)
N=source.N;
L=max(source.layer);
parents=cell(N,1);
for parent=1:N
    children=source.children{parent};
    for k=1:numel(children)
        child=children(k);
        parents{child}(end+1)=parent;
    end
end
indices=cell(L+1,1);
for ell=0:L
    indices{ell+1}=find(source.layer==ell);
end
parentLogic=repmat("AND",N,1);
if strcmp(source.dependencyLogic,'or2')
    parentLogic(source.layer>0)="OR";
end
net=struct('N',N,'L',L,'layer',source.layer, ...
    'layerCounts',cellfun(@numel,indices)', ...
    'layerIndices',{indices},'parents',{parents}, ...
    'children',{source.children},'parentLogic',parentLogic, ...
    'dependencyMode',source.dependencyLogic, ...
    'parentCount',source.parentCount, ...
    'dependencyLogic',source.dependencyLogic, ...
    'duration',source.duration,'weight',source.weight, ...
    'randomPriority',source.randomPriority, ...
    'hybridChoice',source.hybridChoice);
end
