function out=run_coupled_scenario_ensemble(scenario,cfg)

names={'gamma','gB','gBdir','propagationMultiplier','directGateCount', ...
    'gateTargetMet','rho90_0','rho95_0','rho90_c','TEstar','L0','Lc', ...
    'deltaL','epsilonDec','epsilonUB','boundComparable','chiFE','chiFB', ...
    'crewFractionTargetE','crewFractionTargetB','crewCountE','crewCountB', ...
    'crewFractionRealizedE','crewFractionRealizedB','qFE','qFB', ...
    'T90E','T90B0','T90Bc','taskEntropyE','taskEntropyB', ...
    'durationDepthRatioE','durationDepthRatioB','CVdRealizedE', ...
    'CVdRealizedB','CVwRealizedE','CVwRealizedB','rhoDWRealizedE', ...
    'rhoDWRealizedB'};
M=nan(scenario.nRep,numel(names));
example=[];

specE=network_specification(scenario,'E');
specB=network_specification(scenario,'B');
for r=1:scenario.nRep
    [netE,attrsE,realizedE]=make_layered_network( ...
        specE,r,cfg.generator.config,1);
    [netB,attrsB,realizedB]=make_layered_network( ...
        specB,r,cfg.generator.config,2);

    crewsE=max(1,min(netE.N,round(scenario.crewFractionE*netE.N)));
    crewsB=max(1,min(netB.N,round(scenario.crewFractionB*netB.N)));

    QE=sum(attrsE.duration); QB=sum(attrsB.duration);
    scaleB=scenario.gammaTarget*(QE/crewsE)*(crewsB/QB);
    attrsB.duration=attrsB.duration*scaleB;
    netE.duration=attrsE.duration; netE.weight=attrsE.weight;
    netB.duration=attrsB.duration; netB.weight=attrsB.weight;

    [~,simE]=simulate_repair_network_qf(netE,crewsE,scenario.qFE, ...
        cfg.generator.config);
    [~,simB]=simulate_repair_network_qf(netB,crewsB,scenario.qFB, ...
        cfg.generator.config);

    noGateE=false(netE.N,1); noSupportE=zeros(netE.N,1);
    tConnE=service_connection_times(netE,simE.repairFinishTime, ...
        noGateE,noSupportE);
    [tE,RE]=curve_from_connection_times(tConnE,attrsE.weight);
    noGateB=false(netB.N,1); noSupportB=zeros(netB.N,1);
    tConnB0=service_connection_times(netB,simB.repairFinishTime, ...
        noGateB,noSupportB);
    [tB0,RB0]=curve_from_connection_times(tConnB0,attrsB.weight);

    TEstar=milestone_time(tE,RE,scenario.qE,'step');
    repSeed=cfg.baseSeed+2000000+100*r;
    rng(repSeed+4,'twister');
    exposure=construct_gate_set_for_target(netB,attrsB.weight, ...
        scenario.gBTarget,scenario.gateLocation,cfg.coupled.gBTolerance, ...
        cfg.coupled.gateSearchTrials);
    support=zeros(netB.N,1);
    direct=exposure.directGate;
    switch lower(scenario.supportRepresentation)
        case 'aggregate_threshold'
            support(direct)=TEstar; boundComparable=1; maxSupport=TEstar;
        case 'task_specific'
            rng(repSeed+5,'twister');
            support(direct)=sample_support_times( ...
                tConnE,attrsE.weight,nnz(direct));
            boundComparable=0;
            if any(direct), maxSupport=max(support(direct)); else, maxSupport=0; end
        otherwise
            error('Unknown support representation: %s', ...
                scenario.supportRepresentation);
    end

    tConnBc=service_connection_times(netB,simB.repairFinishTime, ...
        direct,support);
    [tBc,RBc]=curve_from_connection_times(tConnBc,attrsB.weight);
    metE=restoration_curve_metrics(tE,RE,'linear');
    metB0=restoration_curve_metrics(tB0,RB0,'linear');
    metBc=restoration_curve_metrics(tBc,RBc,'linear');

    GammaE=sum(attrsE.duration)/crewsE;
    GammaB=sum(attrsB.duration)/crewsB;
    gammaReal=GammaB/GammaE;
    L0=sum(attrsB.weight(:).*tConnB0(:));
    Lc=sum(attrsB.weight(:).*tConnBc(:));
    deltaL=max(0,Lc-L0);
    epsilonDec=deltaL/max(Lc,eps);
    deltaUB=exposure.gB*maxSupport;
    epsilonUB=deltaUB/max(L0+deltaUB,eps);

    M(r,:)=[gammaReal,exposure.gB,exposure.gBdir, ...
        exposure.propagationMultiplier,exposure.directGateCount, ...
        double(exposure.targetMet),metB0.tau90/metE.tau90, ...
        metB0.tau95/metE.tau95,metBc.tau90/metE.tau90,TEstar,L0,Lc, ...
        deltaL,epsilonDec,epsilonUB,boundComparable, ...
        simE.chiFrontier,simB.chiFrontier, ...
        scenario.crewFractionE,scenario.crewFractionB,crewsE,crewsB, ...
        crewsE/netE.N,crewsB/netB.N,scenario.qFE,scenario.qFB, ...
        metE.tau90,metB0.tau90,metBc.tau90, ...
        realizedE.taskLayerEntropyNormalized, ...
        realizedB.taskLayerEntropyNormalized, ...
        realizedE.durationDepthRatio,realizedB.durationDepthRatio, ...
        realizedE.cvDurationWithinLayer,realizedB.cvDurationWithinLayer, ...
        realizedE.cvWeightWithinLayer,realizedB.cvWeightWithinLayer, ...
        realizedE.rhoDurationWeight,realizedB.rhoDurationWeight];

    if isempty(example)
        example=struct('tE',tE,'RE',RE,'tB0',tB0,'RB0',RB0, ...
            'tBc',tBc,'RBc',RBc,'TEstar',TEstar,'exposure',exposure, ...
            'support',support,'netB',netB,'attrsB',attrsB);
    end
end
out=struct('scenario',scenario, ...
    'metrics',array2table(M,'VariableNames',names),'example',example);
end

function specification=network_specification(scenario,systemName)
suffix=upper(systemName);
specification=struct( ...
    'N',scenario.(['N' suffix]), ...
    'maximumDepth',scenario.(['maximumDepth' suffix]), ...
    'taskLayerProfile',scenario.(['taskLayerProfile' suffix]), ...
    'taskCountConcentration',scenario.(['taskCountConcentration' suffix]), ...
    'dependencyMode',scenario.(['dependencyMode' suffix]), ...
    'parentConcentration',scenario.(['parentConcentration' suffix]), ...
    'serviceLayerProfile',scenario.(['serviceLayerProfile' suffix]), ...
    'durationDepthRatio',scenario.(['durationDepthRatio' suffix]), ...
    'CVd',scenario.(['CVd' suffix]), ...
    'CVw',scenario.(['CVw' suffix]), ...
    'rhoDW',scenario.(['rhoDW' suffix]));
end

function x=sample_support_times(tConnE,wE,n)
if n==0, x=zeros(0,1); return; end
w=max(wE(:),0); w=w/max(sum(w),eps); c=cumsum(w);
u=rand(n,1); x=zeros(n,1);
for k=1:n
    idx=find(c>=u(k),1,'first');
    x(k)=tConnE(idx);
end
end
