function run_01_make_loss_compression_late_loss_source_data()

rng(1);
nBoot = 2000;

mainMinPoints = 6;

sysOrder = ["Power", "Water", "Gas"];


moduleRoot = string(fileparts(mfilename("fullpath")));
emergentSimplicityRoot = string(fileparts(fileparts(moduleRoot)));

outputRoot = fullfile( ...
    emergentSimplicityRoot, ...
    "outputs", ...
    "intermediate", ...
    "02_loss_compression_late_loss");

inMat = fullfile( ...
    outputRoot, ...
    "loss_tail_dataset.mat");

ensureDir(outputRoot);

sourceFig3c = fullfile( ...
    outputRoot, ...
    "SourceData_Fig3c_loss_compression.xlsx");

sourceFig3d = fullfile( ...
    outputRoot, ...
    "SourceData_Fig3d_tail_loss90.xlsx");

bootstrapPath = fullfile( ...
    outputRoot, ...
    "loss_compression_bootstrap_slopes.csv");


if ~isfile(inMat)
    error([ ...
        'Prepared loss-tail MAT not found:\n%s\n', ...
        'Run run_00_prepare_loss_tail_dataset.m first.'], ...
        inMat);
end

S = load(inMat, "LossTailRecords");

if ~isfield(S, "LossTailRecords")
    error("MAT file does not contain LossTailRecords:\n%s", inMat);
end

T = normalizeLossTailTable(S.LossTailRecords);

requiredFields = [ ...
    "record_ID", ...
    "system", ...
    "nRestorationRatioPoints", ...
    "Dmax", ...
    "tau50", ...
    "Dmax_tau50", ...
    "Lrest", ...
    "Lrest_over_Dmax_tau50", ...
    "eta90"];

missingFields = requiredFields( ...
    ~ismember(requiredFields, string(T.Properties.VariableNames)));

if ~isempty(missingFields)
    error("LossTailRecords is missing required field(s): %s", ...
        strjoin(missingFields, ", "));
end

preparedRows = height(T);

pointCounts = double(T.nRestorationRatioPoints);

mainMask = ...
    isfinite(pointCounts) & ...
    pointCounts >= mainMinPoints;

T = T(mainMask, :);

if isempty(T)
    error( ...
        "No LossTailRecords satisfy the main-analysis >=%d-point criterion.", ...
        mainMinPoints);
end

fprintf([ ...
    "Prepared input rows: %d | Main-analysis rows (>= %d points): %d\n"], ...
    preparedRows, ...
    mainMinPoints, ...
    height(T));


[LossData, SlopeStats, BootSlopes, CurveRatios] = ...
    buildLossCompressionResults(T, sysOrder, nBoot);

writetable(BootSlopes, bootstrapPath);

FitSummaryExport = formatSlopeSummaryForExport(SlopeStats);
CurveRatioSummaryExport = formatCurveRatioSummaryForExport(CurveRatios);

Fig3cRecordLevel = formatLossRecordLevelForExport(LossData);
Fig3cFitSummary = FitSummaryExport;

writeThreeSheetWorkbook( ...
    sourceFig3c, ...
    "record_level", ...
    Fig3cRecordLevel, ...
    "fit_summary", ...
    Fig3cFitSummary, ...
    "ratio_summary", ...
    CurveRatioSummaryExport);


Tail90 = buildTailLossResults(T, sysOrder);
Tail90SummaryExport = formatTailSummaryForExport(Tail90.summary);

Fig3dRecordLevel = formatTailRecordLevelForExport(Tail90.source);
Fig3dSummary = Tail90SummaryExport;

writeTwoSheetWorkbook( ...
    sourceFig3d, ...
    "record_level", ...
    Fig3dRecordLevel, ...
    "summary", ...
    Fig3dSummary);

fprintf("Loss-compression main-analysis rows (>=6 points): %d\n", height(LossData));
fprintf("Tail-loss eta90 main-analysis rows (>=6 points): %d\n", height(Tail90.source));

fprintf("\nSaved:\n%s\n%s\n%s\n", bootstrapPath, sourceFig3c, sourceFig3d);

end


function T = normalizeLossTailTable(T)
vars = string(T.Properties.VariableNames);
if ismember("System", vars) && ~ismember("system", vars)
    T.Properties.VariableNames{find(vars == "System", 1)} = 'system';
end
vars = string(T.Properties.VariableNames);
if ismember("PeakOutageFraction", vars) && ~ismember("Dmax", vars)
    T.Properties.VariableNames{find(vars == "PeakOutageFraction", 1)} = 'Dmax';
end
if ismember("system", string(T.Properties.VariableNames))
    T.system = normalizeSystemName(T.system);
end
if ismember("record_ID", string(T.Properties.VariableNames))
    T.record_ID = string(T.record_ID);
end
end

function [D, SlopeStats, BootSlopes, CurveRatios] = ...
        buildLossCompressionResults(T, sysOrder, nBoot)

Dmax = double(T.Dmax);
tau50 = double(T.tau50);
Dmax_tau50 = double(T.Dmax_tau50);
Lrest = double(T.Lrest);
Lrest_over_Dmax_tau50 = double(T.Lrest_over_Dmax_tau50);

system = normalizeSystemName(T.system);

keep = ...
    ismember(system, sysOrder) & ...
    isfinite(Dmax) & ...
    isfinite(tau50) & ...
    isfinite(Dmax_tau50) & ...
    isfinite(Lrest) & ...
    isfinite(Lrest_over_Dmax_tau50) & ...
    Dmax > 0 & ...
    tau50 > 0 & ...
    Dmax_tau50 > 0 & ...
    Lrest > 0 & ...
    Lrest_over_Dmax_tau50 > 0;

D = table( ...
    string(T.record_ID(keep)), ...
    system(keep), ...
    Dmax(keep), ...
    tau50(keep), ...
    Dmax_tau50(keep), ...
    Lrest(keep), ...
    Lrest_over_Dmax_tau50(keep), ...
    'VariableNames', { ...
        'record_ID', ...
        'system', ...
        'Dmax', ...
        'tau50', ...
        'Dmax_tau50', ...
        'Lrest', ...
        'Lrest_over_Dmax_tau50'});

groups = ["All systems", sysOrder];

SlopeStats = emptySlopeStats();
BootSlopes = emptyBootSlopes();
CurveRatios = emptyCurveRatioStats();

for g = 1:numel(groups)

    if groups(g) == "All systems"
        idx = true(height(D), 1);
    else
        idx = D.system == groups(g);
    end

    label = groupLabel(groups(g));

    x = double(D.Dmax_tau50(idx));
    y = double(D.Lrest(idx));
    c = double(D.Lrest_over_Dmax_tau50(idx));

    stats = fitThroughOriginWithBootstrap( ...
        x, ...
        y, ...
        nBoot);

    SlopeStats = [ ...
        SlopeStats
        slopeRow(label, nnz(idx), stats)];

    BootSlopes = [ ...
        BootSlopes
        table( ...
            repmat(label, numel(stats.bootSlope), 1), ...
            (1:numel(stats.bootSlope))', ...
            stats.bootSlope(:), ...
            'VariableNames', { ...
                'system', ...
                'bootstrapIndex', ...
                'slope_b'})];

    CurveRatios = [ ...
        CurveRatios
        curveRatioRow(label, c)];
end

end

function stats = fitThroughOriginWithBootstrap(x, y, nBoot)

x = x(:);
y = y(:);

keep = ...
    isfinite(x) & ...
    isfinite(y) & ...
    x > 0 & ...
    y > 0;

x = x(keep);
y = y(keep);

stats = struct( ...
    "slope", NaN, ...
    "R2", NaN, ...
    "bootstrapCiLow", NaN, ...
    "bootstrapCiHigh", NaN, ...
    "bootSlope", NaN(nBoot, 1));

n = numel(x);
sumX2 = sum(x .^ 2);

if n < 2 || sumX2 <= 0
    return;
end

stats.slope = sum(x .* y) / sumX2;

pred = stats.slope .* x;
residual = y - pred;
SSE = sum(residual .^ 2);

SST = sum((y - mean(y)) .^ 2);

if SST > 0
    stats.R2 = 1 - SSE / SST;
end

for b = 1:nBoot

    sampleIndex = randi(n, n, 1);

    xb = x(sampleIndex);
    yb = y(sampleIndex);

    denominator = sum(xb .^ 2);

    if denominator > 0
        stats.bootSlope(b) = ...
            sum(xb .* yb) / denominator;
    end
end

bootstrapValues = stats.bootSlope( ...
    isfinite(stats.bootSlope));

q = quantileLocal( ...
    bootstrapValues, ...
    [0.025 0.975]);

stats.bootstrapCiLow = q(1);
stats.bootstrapCiHigh = q(2);

end

function row = slopeRow(system, n, stats)

row = table( ...
    system, ...
    n, ...
    stats.slope, ...
    stats.bootstrapCiLow, ...
    stats.bootstrapCiHigh, ...
    stats.R2, ...
    'VariableNames', { ...
        'system', ...
        'n', ...
        'slope_b', ...
        'bootstrap_slope_ci95_low', ...
        'bootstrap_slope_ci95_high', ...
        'R2'});

end

function row = curveRatioRow(system, values)

values = values( ...
    isfinite(values) & ...
    values > 0);

q = quantileLocal( ...
    values, ...
    [0.05 0.25 0.50 0.75 0.95]);

row = table( ...
    system, ...
    numel(values), ...
    q(3), ...
    q(2), ...
    q(4), ...
    q(1), ...
    q(5), ...
    'VariableNames', { ...
        'system', ...
        'n', ...
        'median', ...
        'Q25', ...
        'Q75', ...
        'Q05', ...
        'Q95'});

end

function E = emptySlopeStats()

E = table( ...
    strings(0, 1), ...
    zeros(0, 1), ...
    nan(0, 1), ...
    nan(0, 1), ...
    nan(0, 1), ...
    nan(0, 1), ...
    'VariableNames', { ...
        'system', ...
        'n', ...
        'slope_b', ...
        'bootstrap_slope_ci95_low', ...
        'bootstrap_slope_ci95_high', ...
        'R2'});

end

function E = emptyBootSlopes()

E = table( ...
    strings(0, 1), ...
    zeros(0, 1), ...
    nan(0, 1), ...
    'VariableNames', { ...
        'system', ...
        'bootstrapIndex', ...
        'slope_b'});

end

function E = emptyCurveRatioStats()

E = table( ...
    strings(0, 1), ...
    zeros(0, 1), ...
    nan(0, 1), ...
    nan(0, 1), ...
    nan(0, 1), ...
    nan(0, 1), ...
    nan(0, 1), ...
    'VariableNames', { ...
        'system', ...
        'n', ...
        'median', ...
        'Q25', ...
        'Q75', ...
        'Q05', ...
        'Q95'});

end

function Tail = buildTailLossResults(T, sysOrder)

eta90 = double(T.eta90);
system = normalizeSystemName(T.system);

keep = ...
    ismember(system, sysOrder) & ...
    isfinite(eta90) & ...
    eta90 >= 0;

source = table( ...
    string(T.record_ID(keep)), ...
    system(keep), ...
    eta90(keep), ...
    'VariableNames', { ...
        'record_ID', ...
        'system', ...
        'eta90'});

groups = ["All systems", sysOrder];
summary = emptyTailSummary();

for g = 1:numel(groups)

    if groups(g) == "All systems"
        idx = true(height(source), 1);
    else
        idx = source.system == groups(g);
    end

    values = double(source.eta90(idx));

    q = quantileLocal( ...
        values, ...
        [0.05 0.25 0.50 0.75 0.95]);

    summary = [ ...
        summary
        table( ...
            groupLabel(groups(g)), ...
            nnz(idx), ...
            q(3), ...
            q(2), ...
            q(4), ...
            q(1), ...
            q(5), ...
            'VariableNames', { ...
                'system', ...
                'n', ...
                'median', ...
                'Q25', ...
                'Q75', ...
                'Q05', ...
                'Q95'})];
end

Tail = struct( ...
    "source", source, ...
    "summary", summary);

end

function E = emptyTailSummary()

E = table( ...
    strings(0, 1), ...
    zeros(0, 1), ...
    nan(0, 1), ...
    nan(0, 1), ...
    nan(0, 1), ...
    nan(0, 1), ...
    nan(0, 1), ...
    'VariableNames', { ...
        'system', ...
        'n', ...
        'median', ...
        'Q25', ...
        'Q75', ...
        'Q05', ...
        'Q95'});

end

function Out = formatSlopeSummaryForExport(T)

system = string(T.system);
n = double(T.n);
slope_b = double(T.slope_b);

bootstrap_slope_ci95_low = ...
    double(T.bootstrap_slope_ci95_low);

bootstrap_slope_ci95_high = ...
    double(T.bootstrap_slope_ci95_high);

R2 = double(T.R2);

Out = table( ...
    system, ...
    n, ...
    slope_b, ...
    bootstrap_slope_ci95_low, ...
    bootstrap_slope_ci95_high, ...
    R2);

end

function Out = formatCurveRatioSummaryForExport(T)

system = string(T.system);
n = double(T.n);
median = double(T.median);
Q25 = double(T.Q25);
Q75 = double(T.Q75);
Q05 = double(T.Q05);
Q95 = double(T.Q95);

Out = table( ...
    system, ...
    n, ...
    median, ...
    Q25, ...
    Q75, ...
    Q05, ...
    Q95);

end

function Out = formatTailSummaryForExport(T)

system = string(T.system);
n = double(T.n);
median = double(T.median);
Q25 = double(T.Q25);
Q75 = double(T.Q75);
Q05 = double(T.Q05);
Q95 = double(T.Q95);

Out = table( ...
    system, ...
    n, ...
    median, ...
    Q25, ...
    Q75, ...
    Q05, ...
    Q95);

end

function Out = formatLossRecordLevelForExport(D)

record_ID = string(D.record_ID);
system = displaySystemName(D.system);
Dmax = double(D.Dmax);
tau50 = double(D.tau50);
Dmax_tau50 = double(D.Dmax_tau50);
Lrest = double(D.Lrest);

Lrest_over_Dmax_tau50 = ...
    double(D.Lrest_over_Dmax_tau50);

Out = table( ...
    record_ID, ...
    system, ...
    Dmax, ...
    tau50, ...
    Dmax_tau50, ...
    Lrest, ...
    Lrest_over_Dmax_tau50);

end

function Out = formatTailRecordLevelForExport(source)

record_ID = string(source.record_ID);
system = displaySystemName(source.system);
eta90 = double(source.eta90);

Out = table( ...
    record_ID, ...
    system, ...
    eta90);

end

function writeThreeSheetWorkbook( ...
        filename, ...
        sheet1, ...
        T1, ...
        sheet2, ...
        T2, ...
        sheet3, ...
        T3)

if isfile(filename)
    delete(filename);
end

writetable(T1, filename, "Sheet", char(sheet1));
writetable(T2, filename, "Sheet", char(sheet2));
writetable(T3, filename, "Sheet", char(sheet3));

end

function writeTwoSheetWorkbook(filename, sheet1, T1, sheet2, T2)
if isfile(filename)
    delete(filename);
end
writetable(T1, filename, "Sheet", char(sheet1));
writetable(T2, filename, "Sheet", char(sheet2));
end

function ensureDir(d)
if ~isfolder(d)
    mkdir(char(d));
end
end

function q = quantileLocal(vals, probs)
vals = sort(vals(:));
vals = vals(isfinite(vals));
if isempty(vals)
    q = nan(size(probs));
    return;
end
q = nan(size(probs));
for i = 1:numel(probs)
    p = probs(i);
    if isscalar(vals)
        q(i) = vals(1);
    else
        pos = 1 + (numel(vals) - 1) * p;
        lo = floor(pos);
        hi = ceil(pos);
        if lo == hi
            q(i) = vals(lo);
        else
            q(i) = vals(lo) + (vals(hi) - vals(lo)) * (pos - lo);
        end
    end
end
end

function s = normalizeSystemName(s)
s = string(s);
sl = lower(strtrim(s));
s(sl == "all systems" | sl == "all" | sl == "pooled") = "All systems";
s(sl == "e" | sl == "power") = "Power";
s(sl == "w" | sl == "water" | sl == "water supply") = "Water";
s(sl == "g" | sl == "gas" | sl == "natural gas") = "Gas";
end

function s = displaySystemName(s)
s = normalizeSystemName(s);
s(s == "Power") = "Electric power";
s(s == "Water") = "Water supply";
s(s == "Gas") = "Natural gas";
end

function g = groupLabel(g)
if g == "All systems"
    g = "All systems";
elseif g == "Power"
    g = "Electric power";
elseif g == "Water"
    g = "Water supply";
elseif g == "Gas"
    g = "Natural gas";
end
end
