function blockID = af_make_random_block_id(randomBlockID,seedID,cfg)

if ~isscalar(randomBlockID) || ~isfinite(randomBlockID) || ...
        randomBlockID~=floor(randomBlockID) || randomBlockID<1 || ...
        randomBlockID>cfg.nRandomBlocks
    error('RepairTask:InvalidAllFactorRandomBlock', ...
        'randomBlockID must be an integer from 1 to %d.',cfg.nRandomBlocks);
end
if ~isscalar(seedID) || ~isfinite(seedID) || seedID~=floor(seedID) || ...
        seedID<1 || seedID>cfg.nSeeds
    error('RepairTask:InvalidAllFactorSeed', ...
        'seedID must be an integer from 1 to %d.',cfg.nSeeds);
end
blockID=(double(randomBlockID)-1).*cfg.nSeeds+double(seedID);
end
