function [factorInfo,groupInfo] = all_factor_metadata()
factorID=(1:13)';
factorName={ ...
    'n_tasks';'maximum_depth';'task_layer_profile'; ...
    'task_count_concentration';'dependency_logic'; ...
    'parent_concentration';'service_layer_profile'; ...
    'duration_depth_ratio';'cv_duration_within_layer'; ...
    'cv_weight_within_layer';'rho_duration_weight'; ...
    'crew_fraction';'q_f'};
factorLabel={ ...
    'Repair-task count';'Maximum dependency depth'; ...
    'Task-layer profile';'Task-count concentration'; ...
    'Reconnection-prerequisite configuration'; ...
    'Symmetric per-candidate parent-choice concentration (Dirichlet shape alpha_p)'; ...
    'Layer service-share profile'; ...
    'Deep-to-shallow mean-duration ratio'; ...
    'Within-layer repair-duration CV'; ...
    'Within-layer service-weight CV'; ...
    'Duration-service-weight rank-score association'; ...
    'Relative repair capacity, C/N';'Frontier-priority probability, q_F'};
groupID=[ones(6,1);2*ones(5,1);3*ones(2,1)];
groupName=[repmat({'network_architecture'},6,1); ...
    repmat({'task_service_attributes'},5,1); ...
    repmat({'repair_organization'},2,1)];
groupLabel=[repmat({'Task-network architecture'},6,1); ...
    repmat({'Task and service attributes'},5,1); ...
    repmat({'Repair organization'},2,1)];
designSupport={ ...
    '[100,2000], rounded';'{2,4,6,8}'; ...
    '{shallow,uniform,deep}';'[0.5,10]'; ...
    '{single,all-of-two,any-of-two}';'[0.5,10]'; ...
    '{shallow,uniform,intermediate,deep,deep-tail}';'[0.5,2]'; ...
    '[0,2]';'[0,2]';'[-0.6,0.6]';'[0.01,1]';'[0,1]'};
samplingDistribution={ ...
    'log-uniform';'discrete equal weight';'categorical equal weight'; ...
    'log-uniform';'categorical equal weight';'log-uniform'; ...
    'categorical equal weight';'log-uniform';'uniform';'uniform'; ...
    'uniform';'log-uniform';'uniform'};
designRole=repmat({'all-factor Sobol input'},13,1);
factorDefinition={ ...
    'Target number of repair tasks'; ...
    'Maximum number of successive prerequisite layers'; ...
    'Expected distribution of repair-task counts across layers'; ...
    'Total Dirichlet concentration around the task-layer profile'; ...
    'One-parent, all-of-two, or any-of-two reconnection prerequisites'; ...
    ['Symmetric Dirichlet shape assigned to every candidate parent; ' ...
     'N and layer-width interactions remain in total-order effects']; ...
    'Prescribed distribution of total service weight across layers'; ...
    'Deepest- to shallowest-layer mean repair-duration ratio'; ...
    'Target within-layer repair-duration coefficient of variation'; ...
    'Target within-layer service-weight coefficient of variation'; ...
    ['Coefficient coupling normalized duration ranks to service-weight ' ...
     'rank ordering; realized Spearman association is recorded separately']; ...
    'Repair crews as a fraction of repair tasks'; ...
    ['Probability of applying the frontier-first selection rule rather ' ...
     'than the unstructured selection rule when the frontier is nonempty']};
factorInfo=table(factorID,factorName,factorLabel,groupID,groupName, ...
    groupLabel,designSupport,samplingDistribution,designRole,factorDefinition);

groupID=(1:3)';
groupName={'network_architecture';'task_service_attributes'; ...
    'repair_organization'};
groupLabel={'Task-network architecture';'Task and service attributes'; ...
    'Repair organization'};
factorIDList={'1,2,3,4,5,6';'7,8,9,10,11';'12,13'};
groupInfo=table(groupID,groupName,groupLabel,factorIDList);
end
