function metrics=compute_restoration_indicators(trajectory,cfg)
t=trajectory.time(:); R=trajectory.restored(:);
if numel(t)~=numel(R) || numel(t)<2 || t(1)~=0 || ...
        abs(R(1))>cfg.numericTolerance || any(diff(t)<=0) || ...
        any(diff(R)<-cfg.numericTolerance) || ...
        abs(R(end)-1)>100*cfg.numericTolerance
    error('RepairTask:InvalidTrajectory', ...
        'The trajectory must be ordered, monotone and end at full restoration.');
end
metrics=restoration_curve_metrics(t,R,'linear', ...
    cfg.numericTolerance,cfg.milestones);
metrics.step=restoration_curve_metrics(t,R,'step', ...
    cfg.numericTolerance,cfg.milestones);
end
