function file = figure4e_global_sensitivity_matlab(rootDir,mode,dataRoot,outputRoot)
if nargin < 1
    rootDir = fileparts(fileparts(fileparts(mfilename('fullpath'))));
end
if nargin < 2
    mode = 'full';
end

if nargin < 3 || isempty(dataRoot), dataRoot = resolve_figure_data_root(rootDir,mode); end
if nargin < 4 || isempty(outputRoot), outputRoot = resolve_figure_output_root(rootDir,mode); end
sourceFile = fullfile(dataRoot,'Simulation','source_data', ...
    'Fig4e_global_sensitivity.csv');
t = readtable(sourceFile);

outputDir = fullfile(outputRoot,'main');
if ~exist(outputDir,'dir')
    mkdir(outputDir);
end

fontName = 'Arial';
cellFontSize = 8;
rowHeaderFontSize = 8;
columnHeaderFontSize = 9;
titleFontSize = 8.5;

figureSizeCm = [19.5 7.5];
fig = figure('Color','w','Units','centimeters', ...
    'Position',[2 2 figureSizeCm]);
ax = axes(fig,'Position',[0.31 0.10 0.67 0.84]);

outcomeNames = { ...
    'log_tau80_tau50', ...
    'log_tau90_tau80', ...
    'log_tau95_tau90', ...
    'log_kappa', ...
    'logit_eta90'};
columnLabels = { ...
    '$\tau_{80}/\tau_{50}$', ...
    '$\tau_{90}/\tau_{80}$', ...
    '$\tau_{95}/\tau_{90}$', ...
    '$\kappa$', ...
    '$\eta_{90}$'};

rowText = { ...
    'Repair-task count, '; ...
    'Maximum dependency depth, '; ...
    'Task-layer profile'; ...
    'Task-count concentration'; ...
    'Reconnection-prerequisite configuration'; ...
    'Parent-choice concentration, '; ...
    'Layer service-share profile, '; ...
    'Deep-to-shallow duration ratio'; ...
    'Within-layer repair-duration, '; ...
    'Within-layer service-weight, '; ...
    'Duration-service association, '; ...
    'Relative repair capacity, '; ...
    'Frontier-priority probability, '};
rowSymbols = { ...
    '$N$'; ...
    '$L$'; ...
    ''; ...
    ''; ...
    ''; ...
    '$\alpha_p$'; ...
    '$\pi_l$'; ...
    ''; ...
    '$CV_d$'; ...
    '$CV_w$'; ...
    '$\rho_{dw}$'; ...
    '$C/N$'; ...
    '$q_F$'};

blue = [0.173 0.498 0.722];
paleBlue = 0.82+0.18*blue;
outcomeColumn = cellstr(t.outcomeName);
totalOrder = nan(13,5);
firstOrder = nan(13,5);

for row = 1:13
    for column = 1:5
        match = t.factorID == row & ...
            strcmp(outcomeColumn,outcomeNames{column});
        totalOrder(row,column) = 100*t.totalOrderRaw(match);
        firstOrder(row,column) = 100*t.firstOrderRaw(match);
    end
end

hold(ax,'on');
for row = 1:13
    faceColor = [1 1 1];
    if ismember(row,[3 7 12])
        faceColor = paleBlue;
    end

    for column = 1:5
        rectangle(ax,'Position',[column-0.5 row-0.5 1 1], ...
            'FaceColor',faceColor,'EdgeColor',[0.84 0.86 0.88], ...
            'LineWidth',0.55);

        totalValue = totalOrder(row,column);
        firstValue = firstOrder(row,column);
        if round(totalValue,1) == 0
            totalValue = 0;
        end
        if round(firstValue,1) == 0
            firstValue = 0;
        end

        cellText = sprintf('{\\bf %.1f} | %.1f', ...
            totalValue,firstValue);
        text(ax,column,row,cellText, ...
            'HorizontalAlignment','center', ...
            'VerticalAlignment','middle', ...
            'Interpreter','tex', ...
            'FontName',fontName, ...
            'FontSize',cellFontSize, ...
            'BackgroundColor','none', ...
            'EdgeColor','none');
    end
end

plot(ax,[0.5 5.5],[6.5 6.5],'-', ...
    'Color',[0.35 0.38 0.40],'LineWidth',1);
plot(ax,[0.5 5.5],[11.5 11.5],'-', ...
    'Color',[0.35 0.38 0.40],'LineWidth',1);
hold(ax,'off');

set(ax, ...
    'XLim',[0.5 5.5], ...
    'YLim',[0.5 13.5], ...
    'YDir','reverse', ...
    'XTick',1:5, ...
    'XTickLabel',columnLabels, ...
    'YTick',1:13, ...
    'YTickLabel',[], ...
    'TickLength',[0 0], ...
    'FontName',fontName, ...
    'FontSize',rowHeaderFontSize, ...
    'TickLabelInterpreter','latex', ...
    'Box','off');
ax.XAxis.FontSize = columnHeaderFontSize;

for row = 1:13
    draw_mixed_row_label(ax,row,rowText{row},rowSymbols{row}, ...
        fontName,rowHeaderFontSize);
end

title(ax, ...
    'Global sensitivity: total-order | first-order (% of input-driven variance)', ...
    'FontName',fontName, ...
    'FontSize',titleFontSize, ...
    'FontWeight','normal', ...
    'Interpreter','none');
stem=fullfile(outputDir,'Figure4e_global_sensitivity_matlab');
export_publication_figure(fig,stem,450);
file=[stem '.fig'];
close(fig);
end

function draw_mixed_row_label(ax,row,plainText,latexText,fontName,fontSize)
y = 1-(row-0.5)/13;
rightEdge = -0.012;

if isempty(latexText)
    text(ax,rightEdge,y,plainText, ...
        'Units','normalized', ...
        'HorizontalAlignment','right', ...
        'VerticalAlignment','middle', ...
        'Interpreter','none', ...
        'FontName',fontName, ...
        'FontSize',fontSize, ...
        'BackgroundColor','none', ...
        'EdgeColor','none', ...
        'Clipping','off');
    return;
end

symbol = text(ax,rightEdge,y,latexText, ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','middle', ...
    'Interpreter','latex', ...
    'FontSize',fontSize, ...
    'BackgroundColor','none', ...
    'EdgeColor','none', ...
    'Clipping','off');
drawnow;

text(ax,rightEdge-symbol.Extent(3)-0.005,y,plainText, ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','middle', ...
    'Interpreter','none', ...
    'FontName',fontName, ...
    'FontSize',fontSize, ...
    'BackgroundColor','none', ...
    'EdgeColor','none', ...
    'Clipping','off');
end

